### ISSUE TITLE
TimezoneOffsetMeasurementTest.testDifferentTimezones fails locally

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/telemetry-android#64]
Maybe it's because I'm in PST?

```
java.lang.AssertionError: 
Expected :-420
Actual   :-480
 <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.mozilla.telemetry.measurement.TimezoneOffsetMeasurementTest.testDifferentTimezones(TimezoneOffsetMeasurementTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by mcomella** [comment]
Dupe #61.
